services:
  app:
    build: .
    env_file: .env.prod
    volumes:
      - ./conf.json:/app/conf.json
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - minio
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  minio-data:
